services:
  financedb:
    build:
      context: ./MariaDatabase
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE=expenses
      - MARIADB_ROOT_PASSWORD=familyfinance
    ports:
      - '3306:3306'
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -P 3306 -uroot -pfamilyfinance -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_app

  securitydb:
    build:
      context: ./MariaDatabase
      dockerfile: Dockerfile
    environment:
      - MARIADB_DATABASE=users
      - MARIADB_ROOT_PASSWORD=security
    ports:
      - '3307:3306'
    healthcheck:
      test: ["CMD-SHELL", "mariadb -h 127.0.0.1 -P 3306 -uroot -psecurity -e 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_app

  familyfinancespringapp:
    build:
      context: ./FamilyFinance
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - my_app
    depends_on:
      financedb:
        condition: service_healthy

  securityspringapp:
    build:
      context: ./Security
      dockerfile: Dockerfile
    ports:
      - "8070:8070"
    networks:
      - my_app
    depends_on:
      securitydb:
        condition: service_healthy

  gateway:
    build:
      context: ./Gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - my_app
    depends_on:
      - securityspringapp
      - familyfinancespringapp

networks:
  my_app:

